disabled_rules: # các rule loại bỏ
  - trailing_whitespace
opt_in_rules: # các rule được thêm vào
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
excluded: # đường dẫn bỏ qua việc kiểm tra
  - Pods

# hiển thị warning khi sử dụng force casting
force_cast: warning
force_try:
  severity: warning
  
# giới hạn
function_body_length:
  warning: 50
  error: 60
line_length: 120

reporter: "xcode"
